"""tried to add export from vk

Revision ID: 23f2deb975c7
Revises: 4cd4d8822927
Create Date: 2019-05-02 22:20:37.803604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23f2deb975c7'
down_revision = '4cd4d8822927'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('vk_page_url', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'vk_page_url')
    # ### end Alembic commands ###
